defaultPlatforms:
  - linux/arm64/v8
  - linux/amd64

builds:
  - id: connector
    dir: . # default is .
    main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -tags
      - netgo
    ldflags:
      - -s -w
      - -extldflags "-static"
